version: '3.3'

services:

  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"

  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - variables.env
    command: bash -c "gunicorn -b 0.0.0.0:8000 --env DJANGO_CONFIGURATION=Local --workers=2 --timeout=300 --log-level=DEBUG config.wsgi"
    depends_on:
      - db
    volumes:
      - ./klio:/src
      - ./static:/static
    expose:
      - "8000"
    links:
      - db:db

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./klio:/src
      - ./confs/nginx/klio.conf:/etc/nginx/conf.d/nudelaem.conf
      - ./static:/static
    depends_on:
      - web
    links:
      - web:web
