# Generated by Django 2.2.7 on 2020-02-03 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField()),
                ('img', models.ImageField(upload_to='')),
                ('content', models.TextField()),
                ('discount', models.BooleanField(default=False)),
                ('discount_type', models.CharField(blank=True, choices=[('percent', 'Percentage discount'), ('fixed', 'Fixed discount')], max_length=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('total_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('activity', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='special.Special')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.BooleanField(default=False)),
                ('discount_type', models.CharField(blank=True, choices=[('percent', 'Percentage discount'), ('fixed', 'Fixed discount')], max_length=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='special.Special')),
            ],
        ),
    ]
