# Generated by Django 2.2.7 on 2020-02-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='start_date',
            field=models.DateField(),
        ),
    ]
