# Generated by Django 2.2.7 on 2020-02-05 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20200204_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliveryinfo',
            name='to_address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='orderdeliveryinfo',
            name='from_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
    ]
