# Generated by Django 2.2.7 on 2020-02-05 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_auto_20200205_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='basket.OrderDeliveryInfo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='basket.OrderPaymentInfo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='private_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='basket.OrderPrivateInfo'),
        ),
    ]
