# Generated by Django 2.2.7 on 2020-02-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_auto_20200205_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
