# Generated by Django 2.2.7 on 2020-03-25 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200325_1320'),
        ('basket', '0006_auto_20200207_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Basket', 'verbose_name_plural': 'Baskets'},
        ),
        migrations.AlterModelOptions(
            name='basketproduct',
            options={'verbose_name': 'Basket product', 'verbose_name_plural': 'Basket products'},
        ),
        migrations.AlterModelOptions(
            name='orderdeliveryinfo',
            options={'verbose_name': 'Order Delivery Info', 'verbose_name_plural': 'Order Delivery Data'},
        ),
        migrations.AlterModelOptions(
            name='orderpaymentinfo',
            options={'verbose_name': 'Order Payment Info', 'verbose_name_plural': 'Order Payment Data'},
        ),
        migrations.AlterModelOptions(
            name='orderprivateinfo',
            options={'verbose_name': 'Order Private Info', 'verbose_name_plural': 'Order Private Data'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-activity'], 'verbose_name': 'Promo Code', 'verbose_name_plural': 'Promo Codes'},
        ),
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(through='basket.BasketProduct', to='products.Product', verbose_name='products'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='basketproduct',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='added'),
        ),
        migrations.AlterField(
            model_name='basketproduct',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Basket', verbose_name='basket'),
        ),
        migrations.AlterField(
            model_name='basketproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='basketproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Basket', verbose_name='basket'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='basket.OrderDeliveryInfo', verbose_name='delivery info'),
        ),
        migrations.AlterField(
            model_name='order',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='basket.OrderPaymentInfo', verbose_name='payment info'),
        ),
        migrations.AlterField(
            model_name='order',
            name='private_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='basket.OrderPrivateInfo', verbose_name='private info'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo',
            field=models.BooleanField(default=False, verbose_name='promo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=14, verbose_name='promo code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Order is active'), ('pending', 'Order pending'), ('completed', 'Order completed'), ('denied', 'Order denied')], max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='step',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='step'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryinfo',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryinfo',
            name='delivery_terms',
            field=models.BooleanField(default=False, verbose_name='delivery terms'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryinfo',
            name='from_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact', verbose_name='from address'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryinfo',
            name='to_address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='to address'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryinfo',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.City', verbose_name='to city'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryinfo',
            name='to_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.Country', verbose_name='to country'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryinfo',
            name='type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('courier', 'Courier')], max_length=10, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='orderpaymentinfo',
            name='type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Plastic Card'), ('transfer', 'Wire transfer')], max_length=10, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='orderprivateinfo',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=10, verbose_name='client type'),
        ),
        migrations.AlterField(
            model_name='orderprivateinfo',
            name='first_name',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='orderprivateinfo',
            name='last_name',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='orderprivateinfo',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='orderprivateinfo',
            name='personal_data',
            field=models.BooleanField(default=False, verbose_name='personal data'),
        ),
        migrations.AlterField(
            model_name='orderprivateinfo',
            name='phone',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='activity',
            field=models.BooleanField(default=False, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=20, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='deadline',
            field=models.DateField(verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
