# Generated by Django 2.2.7 on 2020-04-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_auto_20200325_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='active',
            new_name='is_active',
        ),
    ]
