# Generated by Django 2.2.7 on 2020-04-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20200406_0138'),
        ('basket', '0009_auto_20200418_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(related_name='baskets', through='basket.BasketProduct', to='products.Product', verbose_name='products'),
        ),
        migrations.AlterUniqueTogether(
            name='basketproduct',
            unique_together={('basket', 'product')},
        ),
    ]
