# Generated by Django 2.2.7 on 2020-04-19 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_auto_20200419_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_basket', to='products.Product', verbose_name='product'),
        ),
    ]
