# Generated by Django 2.2.7 on 2020-04-21 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_auto_20200419_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='basket.OrderDeliveryInfo', verbose_name='delivery info'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='basket.OrderPaymentInfo', verbose_name='payment info'),
        ),
        migrations.AlterField(
            model_name='order',
            name='private_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='basket.OrderPrivateInfo', verbose_name='private info'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Order is active'), ('pending', 'Order pending'), ('completed', 'Order completed'), ('denied', 'Order denied')], default='active', max_length=10, verbose_name='status'),
        ),
    ]
