# Generated by Django 2.2.7 on 2020-04-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0012_auto_20200421_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='basket.OrderDeliveryInfo', verbose_name='delivery info'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='basket.OrderPaymentInfo', verbose_name='payment info'),
        ),
        migrations.AlterField(
            model_name='order',
            name='private_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='basket.OrderPrivateInfo', verbose_name='private info'),
        ),
    ]
