# Generated by Django 2.2.7 on 2020-04-21 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0013_auto_20200421_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='basket.Basket', verbose_name='basket'),
        ),
    ]
