# Generated by Django 2.2.7 on 2020-04-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0014_auto_20200421_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprivateinfo',
            name='first_name',
            field=models.CharField(default=None, max_length=64, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='orderprivateinfo',
            name='last_name',
            field=models.CharField(default=None, max_length=64, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='orderprivateinfo',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=128, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='orderprivateinfo',
            name='phone',
            field=models.CharField(default=None, max_length=64, verbose_name='phone'),
        ),
    ]
