# Generated by Django 2.2.7 on 2020-04-22 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0016_auto_20200422_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliveryinfo',
            name='to_address',
            field=models.CharField(default=1, max_length=512, verbose_name='to address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdeliveryinfo',
            name='to_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.City', verbose_name='to city'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryinfo',
            name='to_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.Country', verbose_name='to country'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryinfo',
            name='type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('courier', 'Courier'), ('courier', 'Transport company')], max_length=10, verbose_name='type'),
        ),
    ]
