# Generated by Django 2.2.7 on 2020-04-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0017_auto_20200422_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliveryinfo',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
