# Generated by Django 2.2.7 on 2020-04-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0018_auto_20200422_1428'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together=set(),
        ),
    ]
