# Generated by Django 2.2.7 on 2020-04-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0020_auto_20200422_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliveryinfo',
            name='to_address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='to address'),
        ),
    ]
