# Generated by Django 2.2.7 on 2020-04-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0021_auto_20200425_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliveryinfo',
            name='type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('courier', 'Courier'), ('courier', 'Transport company')], max_length=20, verbose_name='type'),
        ),
    ]
