# Generated by Django 2.2.7 on 2020-04-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0023_auto_20200425_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='is paid'),
        ),
    ]
