# Generated by Django 2.2.7 on 2020-04-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0024_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='orderdeliveryinfo',
            name='moscow_terms',
            field=models.BooleanField(default=False, verbose_name='moscow terms'),
        ),
    ]
