# Generated by Django 2.2.7 on 2020-04-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0026_auto_20200427_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='received',
            field=models.DateTimeField(verbose_name='received'),
        ),
    ]
