# Generated by Django 2.2.7 on 2020-04-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0030_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='discount amount'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percent', 'Percentage discount'), ('fixed', 'Fixed discount')], default='percent', max_length=10, verbose_name='discount type'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='code'),
        ),
    ]
