# Generated by Django 2.2.7 on 2020-04-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0031_auto_20200427_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketproduct',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inside', to='basket.Basket', verbose_name='basket'),
        ),
    ]
