# Generated by Django 2.2.7 on 2020-04-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0032_auto_20200427_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='received'),
        ),
    ]
