# Generated by Django 2.2.7 on 2020-04-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0034_auto_20200427_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketproduct',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='promo_price'),
        ),
    ]
