# Generated by Django 2.2.7 on 2020-04-29 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0035_basketproduct_promo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliveryinfo',
            name='to_city',
            field=models.ForeignKey(default=351, on_delete=django.db.models.deletion.PROTECT, to='cities_light.City', verbose_name='to city'),
            preserve_default=False,
        ),
    ]
