# Generated by Django 2.2.7 on 2020-04-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0036_auto_20200429_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliveryinfo',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
    ]
