# Generated by Django 2.2.7 on 2020-09-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0038_promocode_for_all_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaymentB2PInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b2p_order_number', models.CharField(max_length=100, verbose_name='best2pay order number')),
                ('b2p_order_register_status', models.CharField(choices=[('progress', 'In progress'), ('fail', 'Fail'), ('success', 'Success')], default='progress', max_length=10, verbose_name='best2pay order register status')),
                ('b2p_order_status', models.CharField(choices=[('progress', 'In progress'), ('fail', 'Fail'), ('success', 'Success')], default='progress', max_length=10, verbose_name='best2pay order status')),
                ('payment_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b2p', to='basket.OrderPaymentInfo')),
            ],
            options={
                'verbose_name': 'Order B2P Registered Payment Info',
                'verbose_name_plural': 'Order B2P Registered Payment Data',
            },
        ),
    ]
