# Generated by Django 2.2.7 on 2020-09-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0039_orderpaymentb2pinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpaymentb2pinfo',
            name='b2p_last_operation_code',
            field=models.IntegerField(default=-1, verbose_name='best2pay last ended operation result code'),
        ),
        migrations.AddField(
            model_name='orderpaymentb2pinfo',
            name='b2p_last_operation_number',
            field=models.IntegerField(default=-1, verbose_name='best2pay last ended operation number'),
        ),
    ]
