# Generated by Django 2.2.7 on 2020-02-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phones',
            field=models.ManyToManyField(related_name='contacts', through='contacts.ContactPhone', to='contacts.Phone'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='label',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile phone'), ('home', 'Home phone'), ('work', 'Work phone')], default=None, max_length=64),
        ),
    ]
