# Generated by Django 2.2.7 on 2020-02-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200204_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='activity',
            field=models.BooleanField(default=True),
        ),
    ]
