# Generated by Django 2.2.7 on 2020-03-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_workinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
