# Generated by Django 2.2.7 on 2020-03-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-activity', 'order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='contactphone',
            options={'ordering': ['-activity', 'main', 'order']},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['-activity', 'phone']},
        ),
        migrations.AlterModelOptions(
            name='socialnet',
            options={'ordering': ['-activity', 'name']},
        ),
        migrations.AddField(
            model_name='socialnet',
            name='activity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialnet',
            name='img',
            field=models.ImageField(default=1, upload_to='socials/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialnet',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='contacts.Contact'),
        ),
    ]
