# Generated by Django 2.2.7 on 2020-03-24 23:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20200319_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-activity', 'order', 'name'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='contactphone',
            options={'ordering': ['-activity', 'main', 'order'], 'verbose_name': 'Contact Phone', 'verbose_name_plural': 'Contact Phones'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['-activity', 'phone'], 'verbose_name': 'Phone', 'verbose_name_plural': 'Phones'},
        ),
        migrations.AlterModelOptions(
            name='socialnet',
            options={'ordering': ['-activity', 'order', 'name'], 'verbose_name': 'Social Net', 'verbose_name_plural': 'Social Nets'},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ['-activity', 'order'], 'verbose_name': 'Working Hours', 'verbose_name_plural': 'Working Hours'},
        ),
        migrations.AddField(
            model_name='workinghours',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='activity'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=256, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.City', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='map',
            field=models.URLField(blank=True, verbose_name='map'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phones',
            field=models.ManyToManyField(related_name='contacts', through='contacts.ContactPhone', to='contacts.Phone', verbose_name='phones'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='main',
            field=models.BooleanField(default=False, verbose_name='main'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Phone', verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='label',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile phone'), ('home', 'Home phone'), ('work', 'Work phone')], default=None, max_length=64, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(default=None, help_text='Enter the phone in the format +7(XXX)XXX-XX-XX', max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='socialnet',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='socialnet',
            name='img',
            field=models.FileField(upload_to='socials/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='socialnet',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='socialnet',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='contacts.Contact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='label',
            field=models.CharField(max_length=32, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='time',
            field=models.CharField(max_length=32, verbose_name='time'),
        ),
    ]
