# Generated by Django 2.2.7 on 2020-06-04 13:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20200325_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='content'),
        ),
    ]
