# Generated by Django 2.2.7 on 2020-01-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('activity', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['activity', 'name'],
            },
        ),
    ]
