# Generated by Django 2.2.7 on 2020-02-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-activity', 'name']},
        ),
    ]
