# Generated by Django 2.2.7 on 2020-03-25 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200204_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-activity', 'last_name', 'username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userphone',
            options={'ordering': ['-activity', 'user', 'phone'], 'verbose_name': 'User Phone', 'verbose_name_plural': 'User Phones'},
        ),
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=256, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.City', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_data',
            field=models.BooleanField(default=False, verbose_name='personal data'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phones',
            field=models.ManyToManyField(related_name='users', through='users.UserPhone', to='contacts.Phone', verbose_name='phones'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registered',
            field=models.DateTimeField(auto_now_add=True, verbose_name='registered'),
        ),
        migrations.AlterField(
            model_name='userphone',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='userphone',
            name='main',
            field=models.BooleanField(default=False, verbose_name='main'),
        ),
        migrations.AlterField(
            model_name='userphone',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='userphone',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Phone', verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='userphone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
