# Generated by Django 2.2.7 on 2020-04-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200410_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True, verbose_name='username'),
        ),
    ]
