# Generated by Django 2.2.7 on 2020-02-05 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200205_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='art',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Brand'),
        ),
    ]
