# Generated by Django 2.2.7 on 2020-02-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200205_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wholesale_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
