# Generated by Django 2.2.7 on 2020-03-21 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('products', '0007_auto_20200320_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='on_main',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CategoryCityRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.City')),
            ],
        ),
    ]
