# Generated by Django 2.2.7 on 2020-03-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200321_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_parent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
