# Generated by Django 2.2.7 on 2020-03-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_has_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-activity', 'order', 'group'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='has_parent',
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.PositiveIntegerField(default=0, editable=False, null=True),
        ),
    ]
