# Generated by Django 2.2.7 on 2020-03-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200321_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='base_ammount',
            new_name='base_amount',
        ),
    ]
