# Generated by Django 2.2.7 on 2020-03-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200204_0845'),
        ('products', '0018_auto_20200323_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='tags.Tag'),
        ),
    ]
