# Generated by Django 2.2.7 on 2020-03-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='property',
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.ManyToManyField(related_name='products', through='products.ProductPropertyValue', to='products.ProductProperty'),
        ),
    ]
