# Generated by Django 2.2.7 on 2020-03-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200324_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended',
            field=models.ManyToManyField(blank=True, related_name='_product_recommended_+', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='productpropertyvalue',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.ProductProperty', verbose_name='Property'),
        ),
    ]
