# Generated by Django 2.2.7 on 2020-03-30 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200330_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.Unit', verbose_name='units'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='products.Unit', verbose_name='units'),
        ),
    ]
