# Generated by Django 2.2.7 on 2020-04-29 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20200428_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'verbose_name': 'Product type', 'verbose_name_plural': 'Product types'},
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='category',
        ),
        migrations.AddField(
            model_name='producttype',
            name='properties',
            field=models.ManyToManyField(related_name='product_types', to='products.ProductProperty', verbose_name='properties'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Brand', verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.DecimalField(decimal_places=4, default=0, help_text='For parents it will be calculated automatically', max_digits=10, null=True, verbose_name='In_stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('unique', 'Unique product'), ('parent', 'Child product'), ('child', 'Parent product')], default='unique', max_length=7, verbose_name='kind'),
        ),
    ]
