# Generated by Django 2.2.7 on 2020-04-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20200429_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('unique', 'Unique product'), ('parent', 'Parent product'), ('child', 'Child product')], default='unique', max_length=7, verbose_name='kind'),
        ),
    ]
