# Generated by Django 2.2.7 on 2020-04-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20200429_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpropertyvalue',
            name='value_date',
        ),
        migrations.RemoveField(
            model_name='productpropertyvalue',
            name='value_file',
        ),
        migrations.RemoveField(
            model_name='productpropertyvalue',
            name='value_image',
        ),
        migrations.RemoveField(
            model_name='productpropertyvalue',
            name='value_richtext',
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('boolean', 'True / False'), ('float', 'Float'), ('datetime', 'Datetime')], default='text', max_length=20, verbose_name='type'),
        ),
    ]
