# Generated by Django 2.2.7 on 2020-04-30 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20200430_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpropertyvalue',
            old_name='prop',
            new_name='property',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, help_text='Choose the product type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.ProductType', verbose_name='product type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended',
            field=models.ManyToManyField(blank=True, help_text='Choose only unique of child products.', related_name='_product_recommended_+', to='products.Product', verbose_name='recommended'),
        ),
        migrations.AlterUniqueTogether(
            name='productpropertyvalue',
            unique_together={('property', 'product')},
        ),
    ]
