# Generated by Django 2.2.7 on 2020-04-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20200430_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='art',
            field=models.IntegerField(blank=True, help_text='Do not set article number for parent product.', null=True, unique=True, verbose_name='vendor code'),
        ),
    ]
