# Generated by Django 2.2.7 on 2020-05-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20200430_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproperty',
            name='interval',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Accuracy between two neighbour values during searching. Used for integer or float types only.', max_digits=6, null=True, verbose_name='property interval'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='slug',
            field=models.SlugField(default=1, max_length=128, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended',
            field=models.ManyToManyField(blank=True, help_text='Choose only unique or child products.', related_name='_product_recommended_+', to='products.Product', verbose_name='recommended'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=128, verbose_name='slug'),
        ),
    ]
