# Generated by Django 2.2.7 on 2020-05-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20200504_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpropertyvalue',
            name='value_datetime',
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('boolean', 'True / False'), ('float', 'Float')], default='text', max_length=20, verbose_name='type'),
        ),
    ]
