# Generated by Django 2.2.7 on 2020-05-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20200504_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Leave blank to fill automatically with name.', max_length=1024, null=True, verbose_name='meta description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Leave blank to fill automatically with words taken from name.', max_length=512, null=True, verbose_name='meta keywords'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Leave blank to fill automatically with name.', max_length=256, null=True, verbose_name='meta title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=4, default=1, help_text='Used for correct displaying and calculating the amount and the price of a product.', max_digits=10, null=True, verbose_name='base amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Leave blank to fill automatically with name.', max_length=1024, null=True, verbose_name='meta description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Leave blank to fill automatically with words taken from name.', max_length=512, null=True, verbose_name='meta keywords'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Leave blank to fill automatically with name.', max_length=256, null=True, verbose_name='meta title'),
        ),
    ]
