# Generated by Django 2.2.7 on 2020-05-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20200505_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='slug'),
        ),
    ]
