# Generated by Django 2.2.7 on 2020-05-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20200505_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='slug',
            field=models.SlugField(help_text='Slug is used for filtration purposes. Use only symbols [a-z,0-9,-]', max_length=128, unique=True, verbose_name='slug'),
        ),
    ]
