# Generated by Django 2.2.7 on 2020-05-24 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20200519_0734'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'slug')},
        ),
    ]
