# Generated by Django 2.2.7 on 2020-06-03 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20200526_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Choose the most detailed category', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='category'),
        ),
    ]
