# Generated by Django 2.2.7 on 2020-06-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_auto_20200606_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='with_filters',
            field=models.BooleanField(default=False, verbose_name='show filters'),
        ),
    ]
