# Generated by Django 2.2.7 on 2020-06-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_category_with_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='interval',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Accuracy between two neighbour values during searching. Used for integer or float types only.', max_digits=8, null=True, verbose_name='property interval'),
        ),
    ]
