# Generated by Django 2.2.7 on 2020-06-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_auto_20200609_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='with_general_img',
            field=models.BooleanField(default=False, verbose_name='show general image'),
        ),
    ]
