# Generated by Django 2.2.7 on 2020-06-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_auto_20200617_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='slug'),
        ),
    ]
