# Generated by Django 2.2.7 on 2020-08-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_auto_20200720_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproperty',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='activity'),
        ),
    ]
