# Generated by Django 2.2.7 on 2020-08-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_productproperty_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productproperty',
            options={'ordering': ['name'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
