# Generated by Django 2.2.7 on 2020-02-08 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_menuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-activity', '-date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-activity', 'order'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='callbackinfo',
            options={'ordering': ['-date'], 'verbose_name': 'Callback info', 'verbose_name_plural': 'Callback info'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['activity'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu item', 'verbose_name_plural': 'Menu items'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-activity', '-date'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['activity', 'name'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='subscriberinfo',
            options={'verbose_name': 'Subscriber info', 'verbose_name_plural': 'Subscriber info'},
        ),
        migrations.AddField(
            model_name='subscriberinfo',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(help_text='Date to be shown in article.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_date',
            field=models.DateTimeField(help_text='Date to make article visible on site.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='At least 1 tag is required.', null=True, to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(help_text='Upload image 1200x675 px.', upload_to=''),
        ),
        migrations.AlterField(
            model_name='callbackinfo',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='callbackinfo',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter the phone in the format +7(XXX)XXX-XX-XX.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(help_text='Date to be shown in article.'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='start_date',
            field=models.DateTimeField(help_text='Date to make article visible on site.'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(help_text='At least 1 tag is required.', to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='subscriberinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='subscriberinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
