# Generated by Django 2.2.7 on 2020-02-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20200208_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(help_text='At least 1 tag is required.', to='tags.Tag'),
        ),
    ]
