# Generated by Django 2.2.7 on 2020-02-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20200208_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriberinfo',
            options={'ordering': ['-date'], 'verbose_name': 'Subscriber info', 'verbose_name_plural': 'Subscriber info'},
        ),
        migrations.AlterField(
            model_name='callbackinfo',
            name='name',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callbackinfo',
            name='phone',
            field=models.CharField(default=1, help_text='Enter the phone in the format +7(XXX)XXX-XX-XX.', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='position',
            field=models.CharField(choices=[(1, 'Header'), (2, 'Footer'), (3, 'Leftbar')], max_length=2),
        ),
        migrations.AlterField(
            model_name='subscriberinfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='subscriberinfo',
            name='name',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
