# Generated by Django 2.2.7 on 2020-02-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20200208_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-activity'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='position',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('leftbar', 'Leftbar')], max_length=2),
        ),
    ]
