# Generated by Django 2.2.7 on 2020-02-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20200208_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='position',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('leftbar', 'Leftbar')], max_length=10),
        ),
    ]
