# Generated by Django 2.2.7 on 2020-02-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200205_2228'),
        ('general', '0007_auto_20200208_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['menu', 'order'], 'verbose_name': 'Menu item', 'verbose_name_plural': 'Menu items'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.Page'),
        ),
    ]
