# Generated by Django 2.2.7 on 2020-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_auto_20200209_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='btn_color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('red', 'Red'), ('white', 'White'), ('black', 'Black')], default='white', max_length=10),
        ),
    ]
