# Generated by Django 2.2.7 on 2020-03-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_auto_20200319_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-activity', 'name'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['menu', 'order', 'name'], 'verbose_name': 'Menu item', 'verbose_name_plural': 'Menu items'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='product',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='related_type',
            field=models.CharField(choices=[('category', 'Category'), ('product', 'Product'), ('page', 'Page')], default='category', max_length=10),
        ),
    ]
