# Generated by Django 2.2.7 on 2020-03-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_auto_20200319_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='related_type',
            field=models.CharField(choices=[('category', 'Category'), ('products', 'Product list'), ('page', 'Page'), ('article', 'Article'), ('news', 'News'), ('external', 'External')], default='category', max_length=10),
        ),
    ]
