# Generated by Django 2.2.7 on 2020-03-25 10:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20200325_0246'),
        ('general', '0014_auto_20200324_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-activity', '-date'], 'verbose_name': 'News item', 'verbose_name_plural': 'News'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tag',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(help_text='At least 1 tag is required.', to='tags.Tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(help_text='At least 1 tag is required.', to='tags.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='activity',
            field=models.BooleanField(default=False, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(help_text='Date to be shown in article.', verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_date',
            field=models.DateTimeField(help_text='Date to make article visible on site.', verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='btn',
            field=models.BooleanField(default=True, verbose_name='button is on'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='btn_color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('red', 'Red'), ('white', 'White'), ('black', 'Black')], default='white', max_length=10, verbose_name='button color'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='btn_text',
            field=models.CharField(blank=True, max_length=32, verbose_name='button text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='content',
            field=models.TextField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='deadline',
            field=models.DateTimeField(help_text='When banner should disappear from a site?', verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(help_text='Upload image 1200x675 px.', upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='start_date',
            field=models.DateTimeField(help_text='From what date banner should be visible on a site?', verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='callbackinfo',
            name='comment',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='callbackinfo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='callbackinfo',
            name='name',
            field=models.CharField(max_length=32, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='callbackinfo',
            name='phone',
            field=models.CharField(help_text='Enter the phone in the format +7(XXX)XXX-XX-XX.', max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='callbackinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=32, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='position',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('leftbar', 'Leftbar')], max_length=10, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link',
            field=models.URLField(blank=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='general.Menu', verbose_name='menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='general.MenuItem', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='related_type',
            field=models.CharField(choices=[('category', 'Category'), ('products', 'Product list'), ('page', 'Page'), ('article', 'Article'), ('news', 'News'), ('external', 'External')], default='category', max_length=10, verbose_name='related type'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='news',
            name='activity',
            field=models.BooleanField(default=False, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(help_text='Date to be shown in article.', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='news',
            name='start_date',
            field=models.DateTimeField(help_text='Date to make article visible on site.', verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='page',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=32, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='subscriberinfo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='subscriberinfo',
            name='name',
            field=models.CharField(max_length=32, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subscriberinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
