# Generated by Django 2.2.7 on 2020-04-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_auto_20200331_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Show article until this date.\n                                                Article will appear forever if this field blank.', null=True, verbose_name='deadline'),
        ),
        migrations.AddField(
            model_name='news',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Show news item until this date.\n                                                News item will appear forever if this field blank.', null=True, verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Date to make article visible on site. \n                                                  Leave this blank to show the article immediately.', null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(help_text='Date to be shown in news.', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Date to make news visible on site. \n                                                  Leave this blank to show the news item immediately.', null=True, verbose_name='start date'),
        ),
    ]
