# Generated by Django 2.2.7 on 2020-04-05 14:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0018_auto_20200403_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Date to make article visible on site.\n                                                  Leave this blank to show the article immediately.', null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='related_type',
            field=models.CharField(choices=[('root', 'Root object'), ('category', 'Category'), ('products', 'Product list'), ('page', 'Info page'), ('article', 'Article'), ('news', 'News'), ('special', 'Special'), ('external', 'External link')], default='category', max_length=10, verbose_name='related type'),
        ),
        migrations.AlterField(
            model_name='news',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Date to make news visible on site.\n                                                  Leave this blank to show the news item immediately.', null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content'),
        ),
    ]
