# Generated by Django 2.2.7 on 2020-04-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_auto_20200405_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='position',
            field=models.CharField(choices=[('header', 'Header'), ('subheader', 'Subheader'), ('footer', 'Footer'), ('leftbar', 'Leftbar')], max_length=10, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link',
            field=models.URLField(blank=True, verbose_name='External link'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='related_type',
            field=models.CharField(choices=[('root', 'Root object'), ('category', 'Category'), ('products', 'Product list'), ('page', 'Info page'), ('article', 'Article'), ('news', 'News'), ('special', 'Special'), ('external', 'External link')], default='category', help_text='\n        Root object - /{object}\n        Category - /categories/{object}\n        Product list - /categories/{object}/products\n        Info page - /info/{object}\n        Article - /articles/{object}\n        News - /news/{object}\n        Special - /specials/{object}\n        External link - {link}\n                                    ', max_length=10, verbose_name='related type'),
        ),
    ]
