# Generated by Django 2.2.7 on 2020-04-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_auto_20200406_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.FileField(blank=True, help_text='Pay attention! Visible ONLY in HEADER SUBMENU! Preferred format - SVG.', upload_to='menu/icons'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(upload_to='articles', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(help_text='Upload image 1200x675 px.', upload_to='banners', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to='news', verbose_name='image'),
        ),
    ]
