# Generated by Django 2.2.7 on 2020-04-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_auto_20200406_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.FileField(blank=True, help_text='Pay attention! Visible ONLY in HEADER SUBMENU! Preferred format - SVG.', upload_to='menu/icons', verbose_name='icon'),
        ),
    ]
