# Generated by Django 2.2.7 on 2020-04-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_auto_20200406_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='icon',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.FileField(blank=True, help_text='Pay attention! Visible ONLY in HEADER SUBMENU! Preferred format - SVG.', upload_to='menu/items/icons', verbose_name='icon'),
        ),
    ]
