# Generated by Django 2.2.7 on 2020-04-23 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0024_auto_20200409_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriberinfo',
            name='name',
        ),
    ]
