# Generated by Django 2.2.7 on 2020-04-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0025_remove_subscriberinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
