# Generated by Django 2.2.7 on 2020-05-19 05:07

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('general', '0029_trgm_postgres_create_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='description')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='sites.Site')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
                'unique_together': {('site', 'description')},
            },
        ),
    ]
