# Generated by Django 2.2.7 on 2020-05-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0030_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='activity'),
        ),
    ]
