# Generated by Django 2.2.7 on 2020-08-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0031_sitesettings_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='show_content',
            field=models.BooleanField(default=True, verbose_name='content is on'),
        ),
    ]
