# Generated by Django 2.2.7 on 2020-02-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='special',
            options={'verbose_name': 'Special', 'verbose_name_plural': 'Specials'},
        ),
        migrations.AlterModelOptions(
            name='specialcategory',
            options={'verbose_name': 'Special Category', 'verbose_name_plural': 'Special Categories'},
        ),
        migrations.AlterModelOptions(
            name='specialproduct',
            options={'verbose_name': 'Special Product', 'verbose_name_plural': 'Special Products'},
        ),
        migrations.RenameField(
            model_name='special',
            old_name='discount_price',
            new_name='discount_amount',
        ),
        migrations.RenameField(
            model_name='specialcategory',
            old_name='discount_price',
            new_name='discount_amount',
        ),
        migrations.RenameField(
            model_name='specialproduct',
            old_name='discount_price',
            new_name='discount_amount',
        ),
    ]
