# Generated by Django 2.2.7 on 2020-02-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20200207_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='total_price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
