# Generated by Django 2.2.7 on 2020-03-21 22:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_discount_price'),
        ('sale', '0004_auto_20200207_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='special',
            options={'ordering': ['-activity'], 'verbose_name': 'Special', 'verbose_name_plural': 'Specials'},
        ),
        migrations.AlterModelOptions(
            name='specialproduct',
            options={'ordering': ['-on_main'], 'verbose_name': 'Special Product', 'verbose_name_plural': 'Special Products'},
        ),
        migrations.RenameField(
            model_name='specialproduct',
            old_name='sale',
            new_name='special',
        ),
        migrations.RemoveField(
            model_name='special',
            name='total_price_min',
        ),
        migrations.AddField(
            model_name='specialproduct',
            name='on_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='special',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='deadline',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='discount',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percent', 'Percentage discount'), ('fixed', 'Fixed discount')], default='percent', max_length=10),
        ),
        migrations.AlterField(
            model_name='special',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='special',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
        migrations.AlterField(
            model_name='special',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 1, 11, 48, 522436)),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specials', to='products.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='specialproduct',
            unique_together={('special', 'product')},
        ),
        migrations.DeleteModel(
            name='SpecialCategory',
        ),
    ]
