# Generated by Django 2.2.7 on 2020-03-21 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20200322_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 1, 23, 40, 980853)),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_relations', to='products.Product'),
        ),
    ]
