# Generated by Django 2.2.7 on 2020-03-21 22:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20200322_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 22, 29, 15, 285449, tzinfo=utc)),
        ),
    ]
