# Generated by Django 2.2.7 on 2020-03-21 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_auto_20200322_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
