# Generated by Django 2.2.7 on 2020-03-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200322_1813'),
        ('sale', '0008_auto_20200322_0130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specialproduct',
            unique_together={('product', 'on_main'), ('special', 'product')},
        ),
    ]
