# Generated by Django 2.2.7 on 2020-03-25 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_auto_20200322_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='activity',
            field=models.BooleanField(default=False, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='special',
            name='content',
            field=models.TextField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='special',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='special',
            name='discount',
            field=models.BooleanField(default=True, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='special',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='discount amount'),
        ),
        migrations.AlterField(
            model_name='special',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percent', 'Percentage discount'), ('fixed', 'Fixed discount')], default='percent', max_length=10, verbose_name='discount type'),
        ),
        migrations.AlterField(
            model_name='special',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='special',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='special',
            name='slug',
            field=models.SlugField(max_length=128, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='special',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='discount amount'),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='on_main',
            field=models.BooleanField(default=False, verbose_name='on main'),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_relations', to='products.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Special', verbose_name='special'),
        ),
    ]
