# Generated by Django 2.2.7 on 2020-04-03 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_auto_20200325_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 11, 3, 12, 651117, tzinfo=utc), help_text='Date of special offer to be shown.', verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='special',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Show special offer until this date.\n                                                Special offer will appear forever if this field is blank.', null=True, verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='special',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Date to make special offer visible on site. \n                                                  Leave this blank to show the special offer immediately.', null=True, verbose_name='start date'),
        ),
    ]
