# Generated by Django 2.2.7 on 2020-04-03 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0011_auto_20200403_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 11, 3, 33, 961558, tzinfo=utc), help_text='Date of special offer to be shown.', verbose_name='published'),
        ),
    ]
