# Generated by Django 2.2.7 on 2020-04-03 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0012_auto_20200403_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of special offer to be shown.', verbose_name='published'),
        ),
    ]
