# Generated by Django 2.2.7 on 2020-04-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20200325_0246'),
        ('sale', '0013_auto_20200403_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='tags',
            field=models.ManyToManyField(help_text='At least 1 tag is required.', to='tags.Tag', verbose_name='tags'),
        ),
    ]
