# Generated by Django 2.2.7 on 2020-04-03 12:41

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0014_special_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='special',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 15, 41, 5, 250716), help_text='Show special offer until this date.\n                                                Special offer will appear forever if this field is blank.', verbose_name='deadline'),
            preserve_default=False,
        ),
    ]
