# Generated by Django 2.2.7 on 2020-04-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20200331_0259'),
        ('sale', '0015_auto_20200403_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='products',
            field=models.ManyToManyField(help_text='At least 1 product is required.', related_name='specials', through='sale.SpecialProduct', to='products.Product', verbose_name='products'),
        ),
    ]
