# Generated by Django 2.2.7 on 2020-04-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0016_special_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Date to make special offer visible on site.\n                                                  Leave this blank to show the special offer immediately.', null=True, verbose_name='start date'),
        ),
    ]
