# Generated by Django 2.2.7 on 2020-04-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0017_auto_20200405_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='threshold',
            field=models.IntegerField(blank=True, null=True, verbose_name='discount threshold'),
        ),
    ]
