# Generated by Django 2.2.7 on 2020-04-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20200420_0223'),
        ('sale', '0018_special_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='categories',
            field=models.ManyToManyField(related_name='specials', to='products.Category', verbose_name='categories'),
        ),
    ]
