# Generated by Django 2.2.7 on 2020-04-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0019_special_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='specials', to='products.Category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='special',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tags.Tag', verbose_name='tags'),
        ),
    ]
