# Generated by Django 2.2.7 on 2020-04-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0020_auto_20200427_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='specials', to='products.Category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='special',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='tags'),
        ),
    ]
