# Generated by Django 2.2.7 on 2020-04-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0021_auto_20200427_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='meta_description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='special',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='meta keywords'),
        ),
        migrations.AddField(
            model_name='special',
            name='meta_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='meta title'),
        ),
    ]
